[package]
name = "switchboard-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "RocksDB-backed KV store and OpenRaft log/state-machine storage"

[dependencies]
switchboard-core = { workspace = true }
serde_json = { workspace = true }
switchboard-wire = { workspace = true }
openraft = { workspace = true }
rocksdb = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
